console.log("Hello World");
console.log("Vishal Deshmukh");
console.log("================================================");
var salary=null;
console.log(typeof salary);
salary=40000;
var typeOfSalary=typeof salary;
console.log("Salary=>",salary,"Type of Salary=>",typeof salary);
salary="foutry thousand";
var typeOfSalary=typeof salary;
console.log("Salary==>",salary,"Type of Salary==>",typeof salary);